### ISSUE TITLE
improvements to the read me instructions

### ISSUE THREAD

**Issue by smatoorian** [sirReeall/vagrant_machines#28]
I have some points that I came across while using this useful tool. it would be good to add these to the instructions;

1)When using the Vagrant up command, the progress % will shows but this will hang on a certain percentage and The creation of the machine will be stopped if Hyper-v is enabled. you need to go to the Windows Feature and disable Hyper-v.

2) What does this tool offer? what should you expect to see once the machine is created.

3) if you have VMware installed, you can still install virtual box but cannot run both together at the same time.( I will update on this point when fully tested my VMware after VB installation)

Thank you

**Comment by Sandalorian** [comment]
Hi @smatoorian 

The system requirements are listed [here](https://github.com/sirReeall/vagrant_machines#requirements) at landing page. I did also add a links back to the requirements on the machines [getting started section](https://github.com/sirReeall/vagrant_machines/blob/master/ActiveDirectory/Windows-2016-std/README.md#geting-started) a few weeks back. 

Check out the README.MD for the file for the machine you are using. If you have any comments on this file or feel it needs to be updated, please submit a PR request for review.

The first and last questions are really outside the scope of what Vagrant repository does. It is not really a install or setup guide for Vagrant, for this you should be looking at Vagrant's documentation.

The issue is that everyone has different configurations setup on their machines. There is no possibility to document and test every configuration. Vagrant is a tool that is support by HashCorp and as such any issues with Vagrant and using combinations of hyper visors on the same machine cannot be fixed here. For example, if you were deploy any Vagrant machine with Virtual Box installed and Hyper-v enabled, you would end up with the same result, regardless of what changes within this repository.
